//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootcamp.FinancialCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int InvoiceId { get; set; }
        public string InvoiceTitle { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public string InvoicePeriod { get; set; }
    }
}
